# 合并井8井3
用清洗好的数据即可，将标签进行更改，油水侵为1，气侵为2，然后onehot编码即可

In [1]:
import numpy as np
import pandas as pd

In [2]:
readpath = r'/home/klmyty/code/ML/data/溢流数据_clean/清洗后数据8_溢流.csv'
df = pd.read_csv(readpath,encoding='GBK')
df

,时间,井深(8004) m,钻头位置(8005) m,迟到井深(8006) m,迟到时间(8007) min,大钩高度(8008) m,大钩负荷(8010) kN,钻压(8011) kN,转盘转速(8012) RPM,扭矩(8013) kN.m,...,甲烷(8212) %,乙烷(8213) %,丙烷(8214) %,正丁烷(8215) %,异丁烷(8216) %,正戊烷(8217) %,异戊烷(8218) %,全烃(8219) %,工况,溢流
0,2020-03-19 20:00:00,2962.02999,2962.02699,2958.93999,42.05159,21.57461,1154.32399,75.77991,54.20431,5.11508,...,0.7680,0.1106,0.03161,0.0031,0.00361,0.0,0.0,1.11658,钻进,0
1,2020-03-19 20:00:01,2962.02999,2962.03199,2958.93999,42.05968,21.56942,1154.15399,75.95031,54.28840,5.07789,...,0.7680,0.1106,0.03161,0.0031,0.00361,0.0,0.0,1.11697,钻进,0
2,2020-03-19 20:00:02,2962.02999,2962.03199,2958.93999,42.05968,21.56942,1154.07500,76.02891,54.36190,4.95509,...,0.7680,0.1106,0.03161,0.0031,0.00361,0.0,0.0,1.11726,钻进,0
3,2020-03-19 20:00:03,2962.02999,2962.03199,2958.93999,42.05968,21.56942,1154.42900,75.67501,54.30380,4.96339,...,0.7680,0.1106,0.03161,0.0031,0.00361,0.0,0.0,1.11766,钻进,0
4,2020-03-19 20:00:04,2962.03998,2962.03798,2958.93999,42.04369,21.56412,1154.29800,75.80601,54.19361,5.11559,...,0.7680,0.1106,0.03161,0.0031,0.00361,0.0,0.0,1.11795,钻进,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14028,2020-03-19 23:59:55,2976.04000,2970.29200,2973.10000,0.00000,13.30980,1279.13700,0.00000,0.00000,0.00000,...,0.0007,0.0000,0.00000,0.0000,0.00000,0.0,0.0,0.03400,关井停钻,0
14029,2020-03-19 23:59:56,2976.04000,2970.29200,2973.10000,0.00000,13.30980,1279.13700,0.00000,0.00000,0.00000,...,0.0007,0.0000,0.00000,0.0000,0.00000,0.0,0.0,0.03400,关井停钻,0
14030,2020-03-19 23:59:57,2976.04000,2970.29200,2973.10000,0.00000,13.30980,1279.15000,0.00000,0.00000,0.00000,...,0.0007,0.0000,0.00000,0.0000,0.00000,0.0,0.0,0.03400,关井停钻,0
14031,2020-03-19 23:59:58,2976.04000,2970.29200,2973.10000,0.00000,13.30980,1279.15000,0.00000,0.00000,0.00000,...,0.0007,0.0000,0.00000,0.0000,0.00000,0.0,0.0,0.03400,关井停钻,0
14032,2020-03-19 23:59:59,2976.04000,2970.29200,2973.10000,0.00000,13.30980,1279.15000,0.00000,0.00000,0.00000,...,0.0007,0.0000,0.00000,0.0000,0.00000,0.0,0.0,0.03390,关井停钻,0

In [3]:
df['溢流'].value_counts()

0    9335
1    4698
Name: 溢流, dtype: int64

In [4]:
readpath2 = r'/home/klmyty/code/ML/data/溢流数据_clean/清洗后数据3_溢流.csv'
df2 = pd.read_csv(readpath2,encoding='GBK')
df2

,时间,井深(8004) m,钻头位置(8005) m,迟到井深(8006) m,大钩高度(8008) m,大钩负荷(8010) kN,钻压(8011) kN,转盘转速(8012) RPM,扭矩(8013) kN.m,累计泵冲总和(8017) stk,...,出口温度(8107) DEG.C,入口电导(8108) s/m,出口电导(8109) s/m,入口流量(8110) L/s,出口流量(百分)(8137) %,出口流量(8111) L/s,总池体积(8112) m3,全烃(8219) %,工况,溢流
0,2020-01-21 12:59:01,3579.26,2250.12,3579.26,36.42999,189.28601,0,0.077,5.00500,0,...,18.08801,0,1.09000,0,0.00000,0,-9999,-9999,关井停钻,0
1,2020-01-21 12:59:03,3579.26,2250.12,3579.26,36.42999,189.28601,0,0.077,5.00500,0,...,18.08801,0,1.09000,0,0.00000,0,-9999,-9999,关井停钻,0
2,2020-01-21 12:59:05,3579.26,2250.12,3579.26,36.42999,189.47701,0,0.077,5.00500,0,...,18.08801,0,1.87999,0,0.00000,0,-9999,-9999,关井停钻,0
3,2020-01-21 12:59:07,3579.26,2250.12,3579.26,36.42999,189.28600,0,0.077,5.00500,0,...,18.08801,0,1.87999,0,0.00000,0,-9999,-9999,关井停钻,0
4,2020-01-21 12:59:09,3579.26,2250.12,3579.26,36.42999,176.85801,0,0.077,5.00001,0,...,18.09401,0,1.09000,0,0.00000,0,-9999,-9999,关井停钻,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5836,2020-01-21 16:16:50,3579.26,2250.57,3579.26,-80.13300,2.66759,0,0.077,5.00499,0,...,15.33800,0,3.75000,0,1.87200,0,-9999,-9999,关井停钻,0
5837,2020-01-21 16:16:52,3579.26,2250.57,3579.26,-80.13300,2.66759,0,0.077,5.00000,0,...,15.35600,0,3.75000,0,1.88099,0,-9999,-9999,关井停钻,0
5838,2020-01-21 16:16:54,3579.26,2250.57,3579.26,-80.13300,2.66759,0,0.077,5.00499,0,...,15.33800,0,4.53000,0,1.87200,0,-9999,-9999,关井停钻,0
5839,2020-01-21 16:16:56,3579.26,2250.57,3579.26,-80.13300,2.66759,0,0.077,5.00499,0,...,15.36900,0,3.75000,0,1.87200,0,-9999,-9999,关井停钻,0
5840,2020-01-21 16:16:58,3579.26,2250.57,3579.26,-80.13300,2.66759,0,0.077,5.00499,0,...,15.36900,0,3.75000,0,1.87200,0,-9999,-9999,关井停钻,0

# 查看两个井的标签

In [5]:
print("井8数据大小",df.shape)
print("井3数据大小",df2.shape)

井8数据大小 (14033, 49)
井3数据大小 (5841, 34)

In [6]:
print("井8溢流标签\n",df['溢流'].value_counts())
print("井3溢流标签\n",df2['溢流'].value_counts())

井8溢流标签
 0    9335
1    4698
Name: 溢流, dtype: int64
井3溢流标签
 0    3961
1    1880
Name: 溢流, dtype: int64

## 井8为油水侵，井3为气侵 故井8的1还为1，井3的1为2

In [7]:
df2.loc[df2['溢流']==1,'溢流'] = 2

In [8]:
print("井3溢流标签\n",df2['溢流'].value_counts())

井3溢流标签
 0    3961
2    1880
Name: 溢流, dtype: int64

# 合并井8井3

In [9]:
data = pd.concat([df, df2], join="inner")

# Select the columns you want to keep
data = data[['井深(8004) m', '迟到井深(8006) m', '大钩高度(8008) m', '全烃(8219) %', '入口温度(8106) DEG.C', '泵冲次1(8059) spm', '出口密度(8105) g/cm3', '套管压力(8019) MPa', '钻时(8020) min/m', '立管压力(8018) MPa', '钻压(8011) kN', '入口流量(8110) L/s', '出口温度(8107) DEG.C', '钻头位置(8005) m', '入口密度(8104) g/cm3', '扭矩(8013) kN.m', '大钩负荷(8010) kN', '总池体积(8112) m3', '溢流', '转盘转速(8012) RPM']]

print(data)

      井深(8004) m  迟到井深(8006) m  大钩高度(8008) m  全烃(8219) %  入口温度(8106) DEG.C  \
0     2962.02999    2958.93999      21.57461     1.11658          39.34880
1     2962.02999    2958.93999      21.56942     1.11697          39.34880
2     2962.02999    2958.93999      21.56942     1.11726          39.34880
3     2962.02999    2958.93999      21.56942     1.11766          39.34880
4     2962.03998    2958.93999      21.56412     1.11795          39.34880
...          ...           ...           ...         ...               ...
5836  3579.26000    3579.26000     -80.13300 -9999.00000          37.93501
5837  3579.26000    3579.26000     -80.13300 -9999.00000          37.94500
5838  3579.26000    3579.26000     -80.13300 -9999.00000          37.93000
5839  3579.26000    3579.26000     -80.13300 -9999.00000          37.93000
5840  3579.26000    3579.26000     -80.13300 -9999.00000          37.93500

      泵冲次1(8059) spm  出口密度(8105) g/cm3  套管压力(8019) MPa  钻时(8020) min/m  \
0                  0           1.60680           0.000         9.28820
1                  0           1.60899           0.000         9.28820
2                  0           1.61079           0.000         9.30390
3                  0           1.61050           0.000         9.32050
4                  0           1.60700           0.000         9.32149
...              ...               ...             ...             ...
5836               0           1.43694           0.012        14.46670
5837               0           1.43694           0.012        14.46670
5838               0           1.43694           0.012        14.46670
5839               0           1.43694           0.012        14.46670
5840               0           1.43694           0.012        14.46670

      立管压力(8018) MPa  钻压(8011) kN  入口流量(8110) L/s  出口温度(8107) DEG.C  \
0           17.82822     75.77991       1678.3872           48.8375
1           17.97551     75.95031       1678.0662           48.8375
2           17.84862     76.02891       1678.0662           48.8375
3           17.64002     75.67501       1678.0662           48.8375
4           17.65231     75.80601       1678.7082           48.8375
...              ...          ...             ...               ...
5836         0.00000      0.00000          0.0000           15.3380
5837         0.00000      0.00000          0.0000           15.3560
5838         0.00000      0.00000          0.0000           15.3380
5839         0.00000      0.00000          0.0000           15.3690
5840         0.00000      0.00000          0.0000           15.3690

      钻头位置(8005) m  入口密度(8104) g/cm3  扭矩(8013) kN.m  大钩负荷(8010) kN  \
0       2962.02699           1.67270        5.11508     1154.32399
1       2962.03199           1.67509        5.07789     1154.15399
2       2962.03199           1.67938        4.95509     1154.07500
3       2962.03199           1.67548        4.96339     1154.42900
4       2962.03798           1.67389        5.11559     1154.29800
...            ...               ...            ...            ...
5836    2250.57000           1.80652        5.00499        2.66759
5837    2250.57000           1.80854        5.00000        2.66759
5838    2250.57000           1.81055        5.00499        2.66759
5839    2250.57000           1.81055        5.00499        2.66759
5840    2250.57000           1.80854        5.00499        2.66759

      总池体积(8112) m3  溢流  转盘转速(8012) RPM
0          80.65078   0        54.20431
1          80.65187   0        54.28840
2          80.64898   0        54.36190
3          80.64329   0        54.30380
4          80.64139   0        54.19361
...             ...  ..             ...
5836    -9999.00000   0         0.07700
5837    -9999.00000   0         0.07700
5838    -9999.00000   0         0.07700
5839    -9999.00000   0         0.07700
5840    -9999.00000   0         0.07700

[19874 rows x 20 columns]

判断是否有列的数值一直没有变化

In [10]:
for column in data.columns:
    if data[column].value_counts().count() == 1:
        print(column)

泵冲次1(8059) spm

<font color='red'>有一直没有变化的列！！！<font>

变化较少的列，少于3的列

In [11]:
for column in data.columns:
    number = data[column].value_counts().count()
    if number <= 3:
        print(column,number)

泵冲次1(8059) spm 1
溢流 3

保存合并好的井1井3数据

In [12]:
data.to_csv('井8井3合并.csv', index=False, mode='w', header=True,encoding='GBK')