# 数据编码onehot

In [27]:
import numpy as np
import pandas as pd
readpath = r'井1井13合并.csv'
data = pd.read_csv(readpath,encoding='GBK')
data.head()

,井深(8004) m,迟到井深(8006) m,大钩高度(8008) m,全烃(8219) %,入口温度(8106) DEG.C,泵冲次1(8059) spm,出口密度(8105) g/cm3,套管压力(8019) MPa,钻时(8020) min/m,立管压力(8018) MPa,钻压(8011) kN,入口流量(8110) L/s,出口温度(8107) DEG.C,钻头位置(8005) m,入口密度(8104) g/cm3,扭矩(8013) kN.m,大钩负荷(8010) kN,总池体积(8112) m3,溢流,转盘转速(8012) RPM
0,3023.54,3023.5,5.46742,0.0678,48.94150,0.0,1.87959,0.0,7.98587,0.0,0.000,0.0,38.27520,1719.02,2.03658,0.0,228.40900,102.26800,0,0.0
1,3023.54,3023.5,5.44833,0.0678,48.91951,0.0,1.87959,0.0,7.98587,0.0,0.000,0.0,38.26581,1719.02,2.03661,0.0,256.32600,102.34000,0,0.0
2,3023.54,3023.5,5.31942,0.0678,48.91951,0.0,1.88025,0.0,7.98587,0.0,0.000,0.0,38.26581,1719.02,2.03661,0.0,239.40600,102.60399,0,0.0
3,3023.54,3023.5,5.30988,0.0678,48.94150,0.0,1.88025,0.0,7.98587,0.0,0.000,0.0,38.27520,1719.02,2.03658,0.0,261.40100,102.43500,0,0.0
4,3023.54,3023.5,5.57726,0.0678,48.91951,0.0,1.88025,0.0,7.98587,0.0,203.975,0.0,38.26581,1719.02,2.03661,0.0,793.15399,102.59900,0,0.0

In [28]:
data.describe()

,井深(8004) m,迟到井深(8006) m,大钩高度(8008) m,全烃(8219) %,入口温度(8106) DEG.C,泵冲次1(8059) spm,出口密度(8105) g/cm3,套管压力(8019) MPa,钻时(8020) min/m,立管压力(8018) MPa,钻压(8011) kN,入口流量(8110) L/s,出口温度(8107) DEG.C,钻头位置(8005) m,入口密度(8104) g/cm3,扭矩(8013) kN.m,大钩负荷(8010) kN,总池体积(8112) m3,溢流,转盘转速(8012) RPM
count,375348.000000,375348.000000,375348.000000,3.753480e+05,375348.000000,375348.000000,375348.000000,3.753480e+05,375348.000000,375348.000000,375348.000000,375348.000000,375348.000000,375348.000000,375348.000000,375348.000000,375348.000000,375348.000000,375348.000000,375348.000000
mean,2701.578070,2697.097023,20.045669,3.782555e+00,51.692934,57.189653,1.570405,1.278834e-01,10.465442,16.997083,61.912905,36.985554,64.112944,2477.560255,1.675707,10.451561,920.287076,135.994009,0.221784,37.720192
std,193.905238,196.384839,9.171366,7.431121e+00,8.403098,29.421432,0.351783,5.108242e-01,6.710516,8.778034,64.381641,18.248175,15.641555,534.088079,0.172711,7.292779,226.210793,16.131532,0.623091,25.340961
min,2357.100000,2350.010000,3.610000,-2.130000e-16,-0.000010,-0.000020,0.040000,-1.940000e-16,2.500000,-0.000020,-484.940990,-0.000010,0.000000,31.400000,-0.000010,-0.000020,0.000000,67.307380,0.000000,-0.000020
25%,2575.930000,2574.480000,12.020010,7.500000e-01,50.139990,60.000000,1.510000,0.000000e+00,5.800000,9.438880,0.000000,25.230020,66.830000,2502.789990,1.530000,0.000000,936.057495,129.380000,0.000000,0.000000
50%,2675.719980,2666.350000,20.610010,1.310000e+00,55.479990,72.339990,1.690000,0.000000e+00,7.985870,22.070010,66.819990,47.450020,70.880000,2615.349990,1.700000,12.510010,966.389990,140.490010,0.000000,54.810020
75%,2802.779992,2799.929990,28.000010,3.800010e+00,57.020000,73.849990,1.730000,0.000000e+00,12.990000,22.680000,127.240010,48.390010,72.640000,2734.530000,1.730000,16.479990,1039.589982,147.780000,0.000000,55.579990
max,3023.540000,3023.500000,37.918970,9.275000e+01,57.590000,172.300000,2.200000,4.339990e+00,34.040000,25.469990,500.000010,68.569980,76.349980,2912.050000,2.190000,27.979980,1488.729980,164.859980,2.000000,88.734410

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375348 entries, 0 to 375347
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   井深(8004) m        375348 non-null  float64
 1   迟到井深(8006) m      375348 non-null  float64
 2   大钩高度(8008) m      375348 non-null  float64
 3   全烃(8219) %        375348 non-null  float64
 4   入口温度(8106) DEG.C  375348 non-null  float64
 5   泵冲次1(8059) spm    375348 non-null  float64
 6   出口密度(8105) g/cm3  375348 non-null  float64
 7   套管压力(8019) MPa    375348 non-null  float64
 8   钻时(8020) min/m    375348 non-null  float64
 9   立管压力(8018) MPa    375348 non-null  float64
 10  钻压(8011) kN       375348 non-null  float64
 11  入口流量(8110) L/s    375348 non-null  float64
 12  出口温度(8107) DEG.C  375348 non-null  float64
 13  钻头位置(8005) m      375348 non-null  float64
 14  入口密度(8104) g/cm3  375348 non-null  float64
 15  扭矩(8013) kN.m     375348 non-null  float64
 16  大钩负荷(8010) kN     375348 non-null  float64
 17  总池体积(8112) m3     375348 non-null  float64
 18  溢流                375348 non-null  int64
 19  转盘转速(8012) RPM    375348 non-null  float64
dtypes: float64(19), int64(1)
memory usage: 57.3 MB

## 找到object类型的特征

In [30]:
# select the columns that are of type object
object_columns = data.select_dtypes(include=['object'])

# get the column names
object_column_names = object_columns.columns.tolist()

print("Columns of type object:", object_column_names)

Columns of type object: []

## 标签编码 onehot 对溢流和工况都进行编码

### get_feature_names_out 方法用于根据原始列名称检索单热编码列的名称。

In [31]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
encoded_kick= encoder.fit_transform(data[['溢流']])
# Create a DataFrame from the encoded data 
encoded_df = pd.DataFrame(encoded_kick.toarray(), columns=encoder.get_feature_names_out(['溢流']))
encoded_df = encoded_df.rename(columns={'溢流_0': 'kick_0', '溢流_1': 'kick_1', '溢流_2': 'kick_2'})

# Concatenate the original DataFrame and the encoded DataFrame
data = pd.concat([data, encoded_df], axis=1)
data.head()

,井深(8004) m,迟到井深(8006) m,大钩高度(8008) m,全烃(8219) %,入口温度(8106) DEG.C,泵冲次1(8059) spm,出口密度(8105) g/cm3,套管压力(8019) MPa,钻时(8020) min/m,立管压力(8018) MPa,...,钻头位置(8005) m,入口密度(8104) g/cm3,扭矩(8013) kN.m,大钩负荷(8010) kN,总池体积(8112) m3,溢流,转盘转速(8012) RPM,kick_0,kick_1,kick_2
0,3023.54,3023.5,5.46742,0.0678,48.94150,0.0,1.87959,0.0,7.98587,0.0,...,1719.02,2.03658,0.0,228.40900,102.26800,0,0.0,1.0,0.0,0.0
1,3023.54,3023.5,5.44833,0.0678,48.91951,0.0,1.87959,0.0,7.98587,0.0,...,1719.02,2.03661,0.0,256.32600,102.34000,0,0.0,1.0,0.0,0.0
2,3023.54,3023.5,5.31942,0.0678,48.91951,0.0,1.88025,0.0,7.98587,0.0,...,1719.02,2.03661,0.0,239.40600,102.60399,0,0.0,1.0,0.0,0.0
3,3023.54,3023.5,5.30988,0.0678,48.94150,0.0,1.88025,0.0,7.98587,0.0,...,1719.02,2.03658,0.0,261.40100,102.43500,0,0.0,1.0,0.0,0.0
4,3023.54,3023.5,5.57726,0.0678,48.91951,0.0,1.88025,0.0,7.98587,0.0,...,1719.02,2.03661,0.0,793.15399,102.59900,0,0.0,1.0,0.0,0.0

In [32]:
list(data['溢流'].values)

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]

In [33]:
data.drop(columns=['溢流'], inplace=True)

## 保存被编码后的数据

In [34]:
data.head()

,井深(8004) m,迟到井深(8006) m,大钩高度(8008) m,全烃(8219) %,入口温度(8106) DEG.C,泵冲次1(8059) spm,出口密度(8105) g/cm3,套管压力(8019) MPa,钻时(8020) min/m,立管压力(8018) MPa,...,出口温度(8107) DEG.C,钻头位置(8005) m,入口密度(8104) g/cm3,扭矩(8013) kN.m,大钩负荷(8010) kN,总池体积(8112) m3,转盘转速(8012) RPM,kick_0,kick_1,kick_2
0,3023.54,3023.5,5.46742,0.0678,48.94150,0.0,1.87959,0.0,7.98587,0.0,...,38.27520,1719.02,2.03658,0.0,228.40900,102.26800,0.0,1.0,0.0,0.0
1,3023.54,3023.5,5.44833,0.0678,48.91951,0.0,1.87959,0.0,7.98587,0.0,...,38.26581,1719.02,2.03661,0.0,256.32600,102.34000,0.0,1.0,0.0,0.0
2,3023.54,3023.5,5.31942,0.0678,48.91951,0.0,1.88025,0.0,7.98587,0.0,...,38.26581,1719.02,2.03661,0.0,239.40600,102.60399,0.0,1.0,0.0,0.0
3,3023.54,3023.5,5.30988,0.0678,48.94150,0.0,1.88025,0.0,7.98587,0.0,...,38.27520,1719.02,2.03658,0.0,261.40100,102.43500,0.0,1.0,0.0,0.0
4,3023.54,3023.5,5.57726,0.0678,48.91951,0.0,1.88025,0.0,7.98587,0.0,...,38.26581,1719.02,2.03661,0.0,793.15399,102.59900,0.0,1.0,0.0,0.0

In [35]:
data.to_csv('井1井13合并_encoded.csv', index=False, mode='w', header=True,encoding='GBK')