# 数据编码onehot

In [11]:
import numpy as np
import pandas as pd
readpath = r'井1井3合并.csv'
data = pd.read_csv(readpath,encoding='GBK')
data.head()

,井深(8004) m,迟到井深(8006) m,大钩高度(8008) m,全烃(8219) %,入口温度(8106) DEG.C,时间,泵冲次1(8059) spm,出口密度(8105) g/cm3,套管压力(8019) MPa,钻时(8020) min/m,...,钻压(8011) kN,入口流量(8110) L/s,出口温度(8107) DEG.C,钻头位置(8005) m,入口密度(8104) g/cm3,扭矩(8013) kN.m,大钩负荷(8010) kN,总池体积(8112) m3,溢流,转盘转速(8012) RPM
0,3023.54,3023.5,5.46742,0.0678,48.94150,2020-01-08 14:00:56,0.0,1.87959,0.0,7.98587,...,0.000,0.0,38.27520,1719.02,2.03658,0.0,228.40900,102.26800,0.0,0.0
1,3023.54,3023.5,5.44833,0.0678,48.91951,2020-01-08 14:00:59,0.0,1.87959,0.0,7.98587,...,0.000,0.0,38.26581,1719.02,2.03661,0.0,256.32600,102.34000,0.0,0.0
2,3023.54,3023.5,5.31942,0.0678,48.91951,2020-01-08 14:01:02,0.0,1.88025,0.0,7.98587,...,0.000,0.0,38.26581,1719.02,2.03661,0.0,239.40600,102.60399,0.0,0.0
3,3023.54,3023.5,5.30988,0.0678,48.94150,2020-01-08 14:01:05,0.0,1.88025,0.0,7.98587,...,0.000,0.0,38.27520,1719.02,2.03658,0.0,261.40100,102.43500,0.0,0.0
4,3023.54,3023.5,5.57726,0.0678,48.91951,2020-01-08 14:01:08,0.0,1.88025,0.0,7.98587,...,203.975,0.0,38.26581,1719.02,2.03661,0.0,793.15399,102.59900,0.0,0.0

In [12]:
data.describe()

,井深(8004) m,迟到井深(8006) m,大钩高度(8008) m,全烃(8219) %,入口温度(8106) DEG.C,泵冲次1(8059) spm,出口密度(8105) g/cm3,套管压力(8019) MPa,钻时(8020) min/m,立管压力(8018) MPa,钻压(8011) kN,入口流量(8110) L/s,出口温度(8107) DEG.C,钻头位置(8005) m,入口密度(8104) g/cm3,扭矩(8013) kN.m,大钩负荷(8010) kN,总池体积(8112) m3,溢流,转盘转速(8012) RPM
count,75164.000000,75164.000000,75164.000000,75164.000000,75164.000000,75164.000000,75164.000000,75164.000000,75164.000000,7.516400e+04,75164.000000,75164.000000,75164.000000,75164.000000,75164.000000,75164.000000,75164.000000,75164.000000,75164.000000,75164.000000
mean,3066.725042,3066.688151,16.625859,-776.114328,35.990506,7.117681,1.508612,0.286149,8.489496,4.119297e+00,-3.105795,7.418416,31.297141,1853.649964,1.804638,1.329443,658.356384,-678.264463,0.190024,6.276556
std,148.775463,148.786171,26.324896,2677.163252,6.355026,18.915262,0.552321,1.006857,1.735026,6.741263e+00,47.697541,11.677967,8.764497,936.995716,0.308002,2.554569,408.309006,2705.573514,0.386351,16.269037
min,3023.540000,3023.500000,-80.133000,-9999.000000,-0.000010,-0.000020,0.736245,-0.517000,7.985870,-8.881784e-16,-484.940990,-0.000010,0.000000,31.400000,-0.000010,-0.000020,-2.868470,-9999.000000,0.000000,-0.000020
25%,3023.540000,3023.500000,12.830000,0.029300,31.117090,0.000000,0.859994,0.000000,7.985870,0.000000e+00,-4.887653,0.000000,23.584500,1469.760000,1.603340,0.000000,259.709010,101.531005,0.000000,0.000000
50%,3023.540000,3023.500000,25.027400,0.029300,37.263385,0.000000,1.838990,0.000000,7.985870,0.000000e+00,0.000000,0.000000,32.129500,2250.570000,1.899220,0.000000,739.551010,106.345010,0.000000,0.000000
75%,3023.540000,3023.500000,29.295333,0.288385,40.577990,0.000000,2.043830,0.000000,7.985870,7.043970e+00,0.000000,15.616400,38.794800,2623.930000,2.077530,0.000010,1073.779990,110.037012,0.500000,0.077000
max,3579.260000,3579.260000,37.918970,33.369180,48.941500,70.000000,2.200000,6.759000,14.466700,2.475460e+01,500.000010,35.827890,48.613100,2912.050000,2.190000,15.837800,1488.729980,133.121970,2.000000,88.734410

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75164 entries, 0 to 75163
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   井深(8004) m        75164 non-null  float64
 1   迟到井深(8006) m      75164 non-null  float64
 2   大钩高度(8008) m      75164 non-null  float64
 3   全烃(8219) %        75164 non-null  float64
 4   入口温度(8106) DEG.C  75164 non-null  float64
 5   时间                75164 non-null  object
 6   泵冲次1(8059) spm    75164 non-null  float64
 7   出口密度(8105) g/cm3  75164 non-null  float64
 8   套管压力(8019) MPa    75164 non-null  float64
 9   钻时(8020) min/m    75164 non-null  float64
 10  立管压力(8018) MPa    75164 non-null  float64
 11  钻压(8011) kN       75164 non-null  float64
 12  入口流量(8110) L/s    75164 non-null  float64
 13  出口温度(8107) DEG.C  75164 non-null  float64
 14  钻头位置(8005) m      75164 non-null  float64
 15  入口密度(8104) g/cm3  75164 non-null  float64
 16  扭矩(8013) kN.m     75164 non-null  float64
 17  大钩负荷(8010) kN     75164 non-null  float64
 18  总池体积(8112) m3     75164 non-null  float64
 19  溢流                75164 non-null  float64
 20  转盘转速(8012) RPM    75164 non-null  float64
dtypes: float64(20), object(1)
memory usage: 12.0+ MB

## 找到object类型的特征

In [14]:
# select the columns that are of type object
object_columns = data.select_dtypes(include=['object'])

# get the column names
object_column_names = object_columns.columns.tolist()

print("Columns of type object:", object_column_names)

Columns of type object: ['时间']

## 标签编码 onehot 对溢流和工况都进行编码

data 数据

prefix='kick' 列的前缀

columns=['溢流'] 要被编码的列

## get_feature_names_out 方法用于根据原始列名称检索单热编码列的名称。

In [20]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
encoded_kick= encoder.fit_transform(data[['溢流']])
# Create a DataFrame from the encoded data 
encoded_df = pd.DataFrame(encoded_kick.toarray(), columns=encoder.get_feature_names_out(['溢流']))
encoded_df = encoded_df.rename(columns={'溢流_0': 'kick_0', '溢流_1': 'kick_1', '溢流_2': 'kick_2'})

# Concatenate the original DataFrame and the encoded DataFrame
df = pd.concat([data, encoded_df], axis=1)
df.head()

,井深(8004) m,迟到井深(8006) m,大钩高度(8008) m,全烃(8219) %,入口温度(8106) DEG.C,时间,泵冲次1(8059) spm,出口密度(8105) g/cm3,套管压力(8019) MPa,钻时(8020) min/m,...,入口密度(8104) g/cm3,扭矩(8013) kN.m,大钩负荷(8010) kN,总池体积(8112) m3,溢流,转盘转速(8012) RPM,溢流_0.0,溢流_0.5,溢流_1.0,溢流_2.0
0,3023.54,3023.5,5.46742,0.0678,48.94150,2020-01-08 14:00:56,0.0,1.87959,0.0,7.98587,...,2.03658,0.0,228.40900,102.26800,0.0,0.0,1.0,0.0,0.0,0.0
1,3023.54,3023.5,5.44833,0.0678,48.91951,2020-01-08 14:00:59,0.0,1.87959,0.0,7.98587,...,2.03661,0.0,256.32600,102.34000,0.0,0.0,1.0,0.0,0.0,0.0
2,3023.54,3023.5,5.31942,0.0678,48.91951,2020-01-08 14:01:02,0.0,1.88025,0.0,7.98587,...,2.03661,0.0,239.40600,102.60399,0.0,0.0,1.0,0.0,0.0,0.0
3,3023.54,3023.5,5.30988,0.0678,48.94150,2020-01-08 14:01:05,0.0,1.88025,0.0,7.98587,...,2.03658,0.0,261.40100,102.43500,0.0,0.0,1.0,0.0,0.0,0.0
4,3023.54,3023.5,5.57726,0.0678,48.91951,2020-01-08 14:01:08,0.0,1.88025,0.0,7.98587,...,2.03661,0.0,793.15399,102.59900,0.0,0.0,1.0,0.0,0.0,0.0

In [ ]:
data.drop(columns=['时间','溢流'], inplace=True)

In [9]:
from joblib import dump
# Save the model to disk
dump(encoded_kick, 'onehotencoder.joblib')

['onehotencoder.joblib']

In [2]:
# encoded = pd.get_dummies(data,prefix=['kick'],columns=['溢流'])
# encoded.head()

,井深(8004) m,迟到井深(8006) m,大钩高度(8008) m,全烃(8219) %,入口温度(8106) DEG.C,时间,泵冲次1(8059) spm,出口密度(8105) g/cm3,套管压力(8019) MPa,钻时(8020) min/m,...,钻头位置(8005) m,入口密度(8104) g/cm3,扭矩(8013) kN.m,大钩负荷(8010) kN,总池体积(8112) m3,转盘转速(8012) RPM,kick_0.0,kick_0.5,kick_1.0,kick_2.0
0,3023.54,3023.5,5.46742,0.0678,48.94150,2020-01-08 14:00:56,0.0,1.87959,0.0,7.98587,...,1719.02,2.03658,0.0,228.40900,102.26800,0.0,1,0,0,0
1,3023.54,3023.5,5.44833,0.0678,48.91951,2020-01-08 14:00:59,0.0,1.87959,0.0,7.98587,...,1719.02,2.03661,0.0,256.32600,102.34000,0.0,1,0,0,0
2,3023.54,3023.5,5.31942,0.0678,48.91951,2020-01-08 14:01:02,0.0,1.88025,0.0,7.98587,...,1719.02,2.03661,0.0,239.40600,102.60399,0.0,1,0,0,0
3,3023.54,3023.5,5.30988,0.0678,48.94150,2020-01-08 14:01:05,0.0,1.88025,0.0,7.98587,...,1719.02,2.03658,0.0,261.40100,102.43500,0.0,1,0,0,0
4,3023.54,3023.5,5.57726,0.0678,48.91951,2020-01-08 14:01:08,0.0,1.88025,0.0,7.98587,...,1719.02,2.03661,0.0,793.15399,102.59900,0.0,1,0,0,0

In [7]:
# encoded.columns

Index(['时间', '井深(8004) m', '钻头位置(8005) m', '迟到井深(8006) m', '大钩高度(8008) m',
       '大钩负荷(8010) kN', '钻压(8011) kN', '转盘转速(8012) RPM', '扭矩(8013) kN.m',
       '立管压力(8018) MPa', '套管压力(8019) MPa', '钻时(8020) min/m',
       '钻井状态参数(8028) None', '钻速(8046) m/hr', '泵冲次1(8059) spm',
       '泵冲次2(8060) spm', '泵冲次3(8061) spm', '入口密度(8104) g/cm3',
       '出口密度(8105) g/cm3', '入口温度(8106) DEG.C', '出口温度(8107) DEG.C',
       '入口电导(8108) s/m', '出口电导(8109) s/m', '入口流量(8110) L/s', '出口流量(8111) L/s',
       '总池体积(8112) m3', '出口流量(百分)(8137) %', '全烃(8219) %', 'kick_0.0',
       'kick_0.5', 'kick_1.0', 'kick_2.0', 'condition_下钻', 'condition_倒划眼',
       'condition_关井停钻', 'condition_划眼', 'condition_卡钻/接', 'condition_循环',
       'condition_未知类型', 'condition_起钻'],
      dtype='object')

## 保存被编码后的数据

保存了无工况被编码的 井1井3合并_encoded

有工况被编码的 井1井3合并_encodedwithconditon.csv

In [3]:
encoded.to_csv('井1井3合并_encodedwithconditon.csv', index=False, mode='w', header=True,encoding='GBK')