In [1]:
import numpy as np
import pandas as pd

In [2]:
readpath = r'/home/klmyty/code/ML/data/溢流数据_clean/清洗后数据1_溢流.csv'
data1 = pd.read_csv(readpath,encoding='GBK')
data1.head()

,时间,井深(8004) m,钻头位置(8005) m,迟到井深(8006) m,大钩高度(8008) m,大钩负荷(8010) kN,钻压(8011) kN,转盘转速(8012) RPM,扭矩(8013) kN.m,立管压力(8018) MPa,...,硫化氢4(8210) ppm,甲烷(8212) %,全烃(8219) %,流量差,累计流量,总池体积差,工况,时间.1,index,溢流
0,2020-01-08 14:00:56,3023.54,1719.02,3023.5,5.46742,228.40900,0.000,0.0,0.0,0.0,...,0.0,0.0678,0.0678,0.00000,0.00000,0.00000,起钻,2020-01-08 14:00:56,0,0.0
1,2020-01-08 14:00:59,3023.54,1719.02,3023.5,5.44833,256.32600,0.000,0.0,0.0,0.0,...,0.0,0.0678,0.0678,0.00008,0.00000,0.07200,起钻,2020-01-08 14:00:59,1,0.0
2,2020-01-08 14:01:02,3023.54,1719.02,3023.5,5.31942,239.40600,0.000,0.0,0.0,0.0,...,0.0,0.0678,0.0678,-0.00001,0.00008,0.26399,起钻,2020-01-08 14:01:02,2,0.0
3,2020-01-08 14:01:05,3023.54,1719.02,3023.5,5.30988,261.40100,0.000,0.0,0.0,0.0,...,0.0,0.0678,0.0678,-0.00003,0.00007,-0.16899,起钻,2020-01-08 14:01:05,3,0.0
4,2020-01-08 14:01:08,3023.54,1719.02,3023.5,5.57726,793.15399,203.975,0.0,0.0,0.0,...,0.0,0.0678,0.0678,0.00000,0.00004,0.16400,起钻,2020-01-08 14:01:08,4,0.0

In [3]:
readpath = r'/home/klmyty/code/ML/data/溢流数据_clean/清洗后数据3_溢流.csv'
data3 = pd.read_csv(readpath,encoding='GBK')
data3.head()

,时间,井深(8004) m,钻头位置(8005) m,迟到井深(8006) m,大钩高度(8008) m,大钩负荷(8010) kN,钻压(8011) kN,转盘转速(8012) RPM,扭矩(8013) kN.m,累计泵冲总和(8017) stk,...,出口温度(8107) DEG.C,入口电导(8108) s/m,出口电导(8109) s/m,入口流量(8110) L/s,出口流量(百分)(8137) %,出口流量(8111) L/s,总池体积(8112) m3,全烃(8219) %,工况,溢流
0,2020-01-21 12:59:01,3579.26,2250.12,3579.26,36.42999,189.28601,0,0.077,5.00500,0,...,18.08801,0,1.09000,0,0.0,0,-9999,-9999,关井停钻,0
1,2020-01-21 12:59:03,3579.26,2250.12,3579.26,36.42999,189.28601,0,0.077,5.00500,0,...,18.08801,0,1.09000,0,0.0,0,-9999,-9999,关井停钻,0
2,2020-01-21 12:59:05,3579.26,2250.12,3579.26,36.42999,189.47701,0,0.077,5.00500,0,...,18.08801,0,1.87999,0,0.0,0,-9999,-9999,关井停钻,0
3,2020-01-21 12:59:07,3579.26,2250.12,3579.26,36.42999,189.28600,0,0.077,5.00500,0,...,18.08801,0,1.87999,0,0.0,0,-9999,-9999,关井停钻,0
4,2020-01-21 12:59:09,3579.26,2250.12,3579.26,36.42999,176.85801,0,0.077,5.00001,0,...,18.09401,0,1.09000,0,0.0,0,-9999,-9999,关井停钻,0

In [4]:
readpath = r'/home/klmyty/code/ML/data/溢流数据_clean/清洗后数据8_溢流.csv'
data8 = pd.read_csv(readpath,encoding='GBK')
data8.head()

,时间,井深(8004) m,钻头位置(8005) m,迟到井深(8006) m,迟到时间(8007) min,大钩高度(8008) m,大钩负荷(8010) kN,钻压(8011) kN,转盘转速(8012) RPM,扭矩(8013) kN.m,...,甲烷(8212) %,乙烷(8213) %,丙烷(8214) %,正丁烷(8215) %,异丁烷(8216) %,正戊烷(8217) %,异戊烷(8218) %,全烃(8219) %,工况,溢流
0,2020-03-19 20:00:00,2962.02999,2962.02699,2958.93999,42.05159,21.57461,1154.32399,75.77991,54.20431,5.11508,...,0.768,0.1106,0.03161,0.0031,0.00361,0.0,0.0,1.11658,钻进,0
1,2020-03-19 20:00:01,2962.02999,2962.03199,2958.93999,42.05968,21.56942,1154.15399,75.95031,54.28840,5.07789,...,0.768,0.1106,0.03161,0.0031,0.00361,0.0,0.0,1.11697,钻进,0
2,2020-03-19 20:00:02,2962.02999,2962.03199,2958.93999,42.05968,21.56942,1154.07500,76.02891,54.36190,4.95509,...,0.768,0.1106,0.03161,0.0031,0.00361,0.0,0.0,1.11726,钻进,0
3,2020-03-19 20:00:03,2962.02999,2962.03199,2958.93999,42.05968,21.56942,1154.42900,75.67501,54.30380,4.96339,...,0.768,0.1106,0.03161,0.0031,0.00361,0.0,0.0,1.11766,钻进,0
4,2020-03-19 20:00:04,2962.03998,2962.03798,2958.93999,42.04369,21.56412,1154.29800,75.80601,54.19361,5.11559,...,0.768,0.1106,0.03161,0.0031,0.00361,0.0,0.0,1.11795,钻进,0

In [5]:
readpath = r'/home/klmyty/code/ML/data/溢流数据_clean/清洗后数据12_溢流.csv'
data12 = pd.read_csv(readpath,encoding='GBK')
data12.head()

,时间,井深(8004) m,钻头位置(8005) m,迟到井深(8006) m,迟到时间(8007) min,大钩高度(8008) m,大钩负荷(8010) kN,钻压(8011) kN,转盘转速(8012) RPM,扭矩(8013) kN.m,...,正丁烷(8215) %,异丁烷(8216) %,正戊烷(8217) %,异戊烷(8218) %,全烃(8219) %,总池体积差,累计总池体积差,工况,时间.1,溢流
0,2020/4/30 0:00,2361.16998,2361.16998,2353.19999,46,27.83001,1021.29000,170.69000,60.10001,12.30000,...,0.0,0.0,0.0,0.0,1.72999,0.00000,0.00000,钻进,2020/4/30 0:00,0
1,2020/4/30 0:00,2361.17997,2361.17997,2353.19999,46,27.82002,1021.29000,170.68001,60.02002,12.48999,...,0.0,0.0,0.0,0.0,1.72999,0.02000,0.00000,钻进,2020/4/30 0:00,0
2,2020/4/30 0:00,2361.18997,2361.18997,2353.19999,46,27.81002,1024.10999,167.85001,60.02002,12.48999,...,0.0,0.0,0.0,0.0,1.71999,0.08999,0.02000,钻进,2020/4/30 0:00,0
3,2020/4/30 0:00,2361.19996,2361.19996,2353.22999,46,27.80003,1023.21000,168.75001,60.16001,12.27999,...,0.0,0.0,0.0,0.0,1.72999,0.15000,0.10999,钻进,2020/4/30 0:00,0
4,2020/4/30 0:00,2361.20996,2361.20996,2353.22999,46,27.79003,1023.21000,168.74002,60.02002,12.07000,...,0.0,0.0,0.0,0.0,1.72999,0.17000,0.25999,钻进,2020/4/30 0:00,0

In [6]:
readpath = r'/home/klmyty/code/ML/data/溢流数据_clean/清洗后数据13_溢流.csv'
data13 = pd.read_csv(readpath,encoding='GBK')
data13.head()

,时间,井深(8004) m,钻头位置(8005) m,迟到井深(8006) m,迟到时间(8007) min,大钩高度(8008) m,大钩速度(8009) m/s,大钩负荷(8010) kN,钻压(8011) kN,转盘转速(8012) RPM,...,丙烷(8214) %,正丁烷(8215) %,异丁烷(8216) %,异戊烷(8218) %,全烃(8219) %,总池体积差,累计总池体积差,工况,时间.1,溢流
0,2020/5/2 8:00,2357.1,2354.62,2350.01,50.63,6.98,0.0,991.20999,0.0,54.56000,...,0.02001,0,0,0,1.05,0.00000,0.00000,倒划眼,2020/5/2 8:00,0
1,2020/5/2 8:00,2357.1,2354.62,2350.01,51.27,6.98,0.0,995.31999,0.0,54.59000,...,0.02001,0,0,0,1.05,0.03999,0.00000,倒划眼,2020/5/2 8:00,0
2,2020/5/2 8:00,2357.1,2354.62,2350.01,51.52,6.98,0.0,998.00998,0.0,54.95999,...,0.02001,0,0,0,1.05,-0.01999,0.03999,倒划眼,2020/5/2 8:00,0
3,2020/5/2 8:00,2357.1,2354.62,2350.01,51.17,6.98,0.0,996.30998,0.0,55.22998,...,0.02001,0,0,0,1.04,-0.03000,0.02000,倒划眼,2020/5/2 8:00,0
4,2020/5/2 8:00,2357.1,2354.62,2350.01,50.68,6.98,0.0,996.16999,0.0,55.08999,...,0.02001,0,0,0,1.04,0.03000,-0.01000,倒划眼,2020/5/2 8:00,0

In [7]:
readpath = r'/home/klmyty/code/ML/data/溢流数据_clean/清洗后数据19_溢流.csv'
data19 = pd.read_csv(readpath,encoding='GBK')
data19.head()

,时间,井深(8004) m,钻头位置(8005) m,迟到井深(8006) m,迟到时间(8007) min,大钩高度(8008) m,大钩速度(8009) m/s,大钩负荷(8010) kN,钻压(8011) kN,转盘转速(8012) RPM,...,正戊烷(8217) %,异戊烷(8218) %,全烃(8219) %,流量差,累计流量,总池体积差,工况,时间.1,index,溢流
0,2020-08-25 00:00:00,7003.14,1090.34999,7003.14,0.0,36.11,-0.00001,248.76002,0.0,0.0,...,0.0,0.0,0.01,0.0,0.0,0.00000,关井/停,2020-08-25 00:00:00,0,0.0
1,2020-08-25 00:00:01,7003.14,1090.34999,7003.14,0.0,36.11,-0.00001,248.68003,0.0,0.0,...,0.0,0.0,0.01,0.0,0.0,0.00999,关井/停,2020-08-25 00:00:01,1,0.0
2,2020-08-25 00:00:02,7003.14,1090.34999,7003.14,0.0,36.11,-0.00001,248.79002,0.0,0.0,...,0.0,0.0,0.01,0.0,0.0,0.00999,关井/停,2020-08-25 00:00:02,2,0.0
3,2020-08-25 00:00:03,7003.14,1090.34999,7003.14,0.0,36.11,0.00000,248.05000,0.0,0.0,...,0.0,0.0,0.01,0.0,0.0,-0.00995,关井/停,2020-08-25 00:00:03,3,0.0
4,2020-08-25 00:00:04,7003.14,1090.34999,7003.14,0.0,36.11,0.00000,248.08000,0.0,0.0,...,0.0,0.0,0.01,0.0,0.0,0.00999,关井/停,2020-08-25 00:00:04,4,0.0

## 查看所有井的数据大小

井1,8,12为油水侵，井3,13,19为气侵

In [10]:
data1.shape,data8.shape,data12.shape

((69323, 45), (14033, 49), (85021, 53))

In [11]:
data3.shape,data13.shape,data19.shape

((5841, 34), (306025, 56), (603238, 65))

可以看出井1和井13的数据量差不多，故使用井1和井13进行合并

合并8和2来进行测试，数量较少

In [2]:
import glob


# Use glob to find all CSV files in the folder
path = '/home/klmyty/code/ML/data/溢流数据_clean/*.csv'
csv_files = glob.glob(path)

# Read each CSV file into a separate dataframe
dfs = [pd.read_csv(file,encoding='GBK') for file in csv_files]

intersection 它返回两个或多个集合之间的公共元素。公共元素在新集合中返回。

In [5]:
# Find the common columns between dataframes in the list
common_columns = set(dfs[0].columns).intersection(*(set(df.columns) for df in dfs))

print(f"The common columns between the dataframes are: {common_columns}")

The common columns between the dataframes are: {'工况', '井深(8004) m', '迟到井深(8006) m', '大钩高度(8008) m', '全烃(8219) %', '入口温度(8106) DEG.C', '时间', '泵冲次1(8059) spm', '出口密度(8105) g/cm3', '套管压力(8019) MPa', '钻时(8020) min/m', '立管压力(8018) MPa', '钻压(8011) kN', '入口流量(8110) L/s', '出口温度(8107) DEG.C', '钻头位置(8005) m', '入口密度(8104) g/cm3', '扭矩(8013) kN.m', '大钩负荷(8010) kN', '总池体积(8112) m3', '溢流', '转盘转速(8012) RPM'}

## 所有数据中都有的数据为

'工况', '井深(8004) m', '迟到井深(8006) m', '大钩高度(8008) m', '全烃(8219) %', '入口温度(8106) DEG.C', '时间', '泵冲次1(8059) spm', '出口密度(8105) g/cm3', '套管压力(8019) MPa', '钻时(8020) min/m', '立管压力(8018) MPa', '钻压(8011) kN', '入口流量(8110) L/s', '出口温度(8107) DEG.C', '钻头位置(8005) m', '入口密度(8104) g/cm3', '扭矩(8013) kN.m', '大钩负荷(8010) kN', '总池体积(8112) m3', '溢流', '转盘转速(8012) RPM'

由于使用onehot编码可能会有的井有些工况没有，故先将工况删除，先看看结果如何

In [6]:
list = ['井深(8004) m', '迟到井深(8006) m', '大钩高度(8008) m', '全烃(8219) %', '入口温度(8106) DEG.C', '时间', '泵冲次1(8059) spm', '出口密度(8105) g/cm3', '套管压力(8019) MPa', '钻时(8020) min/m', '立管压力(8018) MPa', '钻压(8011) kN', '入口流量(8110) L/s', '出口温度(8107) DEG.C', '钻头位置(8005) m', '入口密度(8104) g/cm3', '扭矩(8013) kN.m', '大钩负荷(8010) kN', '总池体积(8112) m3', '溢流', '转盘转速(8012) RPM']
len(list)

21

In [12]:
data1['溢流'].values

array([0., 0., 0., ..., 0., 0., 0.])

In [13]:
data3['溢流'].values

array([0, 0, 0, ..., 0, 0, 0])

In [14]:
data8['溢流'].values

array([0, 0, 0, ..., 0, 0, 0])

In [15]:
data13['溢流'].values

array([0, 0, 0, ..., 0, 0, 0])