## 使用其他井数据进行测试

发现问题，重新建模

In [17]:
import numpy as np
import pandas as pd
readpath = r'/home/klmyty/code/ML/data/溢流数据_clean/清洗后数据13_溢流.csv'
data = pd.read_csv(readpath,encoding='GBK')
data.head()

,时间,井深(8004) m,钻头位置(8005) m,迟到井深(8006) m,迟到时间(8007) min,大钩高度(8008) m,大钩速度(8009) m/s,大钩负荷(8010) kN,钻压(8011) kN,转盘转速(8012) RPM,...,丙烷(8214) %,正丁烷(8215) %,异丁烷(8216) %,异戊烷(8218) %,全烃(8219) %,总池体积差,累计总池体积差,工况,时间.1,溢流
0,2020/5/2 8:00,2357.1,2354.62,2350.01,50.63,6.98,0.0,991.20999,0.0,54.56000,...,0.02001,0,0,0,1.05,0.00000,0.00000,倒划眼,2020/5/2 8:00,0
1,2020/5/2 8:00,2357.1,2354.62,2350.01,51.27,6.98,0.0,995.31999,0.0,54.59000,...,0.02001,0,0,0,1.05,0.03999,0.00000,倒划眼,2020/5/2 8:00,0
2,2020/5/2 8:00,2357.1,2354.62,2350.01,51.52,6.98,0.0,998.00998,0.0,54.95999,...,0.02001,0,0,0,1.05,-0.01999,0.03999,倒划眼,2020/5/2 8:00,0
3,2020/5/2 8:00,2357.1,2354.62,2350.01,51.17,6.98,0.0,996.30998,0.0,55.22998,...,0.02001,0,0,0,1.04,-0.03000,0.02000,倒划眼,2020/5/2 8:00,0
4,2020/5/2 8:00,2357.1,2354.62,2350.01,50.68,6.98,0.0,996.16999,0.0,55.08999,...,0.02001,0,0,0,1.04,0.03000,-0.01000,倒划眼,2020/5/2 8:00,0

In [19]:
data = data[['井深(8004) m', '迟到井深(8006) m', '大钩高度(8008) m', '全烃(8219) %', '入口温度(8106) DEG.C', '时间', '泵冲次1(8059) spm', '出口密度(8105) g/cm3', '套管压力(8019) MPa', '钻时(8020) min/m', '立管压力(8018) MPa', '钻压(8011) kN', '入口流量(8110) L/s', '出口温度(8107) DEG.C', '钻头位置(8005) m', '入口密度(8104) g/cm3', '扭矩(8013) kN.m', '大钩负荷(8010) kN', '总池体积(8112) m3', '溢流', '转盘转速(8012) RPM']]

## onehot

In [4]:
encoded = pd.get_dummies(data,prefix=['kick'],columns=['溢流'])
encoded.head()

,井深(8004) m,迟到井深(8006) m,大钩高度(8008) m,全烃(8219) %,入口温度(8106) DEG.C,时间,泵冲次1(8059) spm,出口密度(8105) g/cm3,套管压力(8019) MPa,钻时(8020) min/m,...,入口流量(8110) L/s,出口温度(8107) DEG.C,钻头位置(8005) m,入口密度(8104) g/cm3,扭矩(8013) kN.m,大钩负荷(8010) kN,总池体积(8112) m3,转盘转速(8012) RPM,kick_0,kick_1
0,2962.02999,2958.93999,21.57461,1.11658,39.3488,2020-03-19 20:00:00,0,1.60680,0.0,9.28820,...,1678.3872,48.8375,2962.02699,1.67270,5.11508,1154.32399,80.65078,54.20431,1,0
1,2962.02999,2958.93999,21.56942,1.11697,39.3488,2020-03-19 20:00:01,0,1.60899,0.0,9.28820,...,1678.0662,48.8375,2962.03199,1.67509,5.07789,1154.15399,80.65187,54.28840,1,0
2,2962.02999,2958.93999,21.56942,1.11726,39.3488,2020-03-19 20:00:02,0,1.61079,0.0,9.30390,...,1678.0662,48.8375,2962.03199,1.67938,4.95509,1154.07500,80.64898,54.36190,1,0
3,2962.02999,2958.93999,21.56942,1.11766,39.3488,2020-03-19 20:00:03,0,1.61050,0.0,9.32050,...,1678.0662,48.8375,2962.03199,1.67548,4.96339,1154.42900,80.64329,54.30380,1,0
4,2962.03998,2958.93999,21.56412,1.11795,39.3488,2020-03-19 20:00:04,0,1.60700,0.0,9.32149,...,1678.7082,48.8375,2962.03798,1.67389,5.11559,1154.29800,80.64139,54.19361,1,0

## 使用labelencoder

In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['溢流'] = le.fit_transform(data['溢流'])
# data['工况'] = le.fit_transform(data['工况'])
data.head()

,井深(8004) m,迟到井深(8006) m,大钩高度(8008) m,全烃(8219) %,入口温度(8106) DEG.C,时间,泵冲次1(8059) spm,出口密度(8105) g/cm3,套管压力(8019) MPa,钻时(8020) min/m,...,钻压(8011) kN,入口流量(8110) L/s,出口温度(8107) DEG.C,钻头位置(8005) m,入口密度(8104) g/cm3,扭矩(8013) kN.m,大钩负荷(8010) kN,总池体积(8112) m3,溢流,转盘转速(8012) RPM
0,2357.1,2350.01,6.98,1.05,48.06000,2020/5/2 8:00,79.25001,1.48,0.0,3.59,...,0.0,52.15001,63.68999,2354.62,1.5,12.32000,991.20999,137.59999,0,54.56000
1,2357.1,2350.01,6.98,1.05,48.06000,2020/5/2 8:00,78.34002,1.48,0.0,3.59,...,0.0,51.50002,63.68999,2354.62,1.5,12.07000,995.31999,137.63998,0,54.59000
2,2357.1,2350.01,6.98,1.05,48.06000,2020/5/2 8:00,77.93003,1.47,0.0,3.59,...,0.0,51.25002,63.68999,2354.62,1.5,8.62000,998.00998,137.61999,0,54.95999
3,2357.1,2350.01,6.98,1.04,48.06999,2020/5/2 8:00,78.48002,1.48,0.0,3.59,...,0.0,51.60002,63.68999,2354.62,1.5,6.41001,996.30998,137.58999,0,55.22998
4,2357.1,2350.01,6.98,1.04,48.06000,2020/5/2 8:00,79.20001,1.48,0.0,3.59,...,0.0,52.10002,63.68999,2354.62,1.5,7.72000,996.16999,137.61999,0,55.08999

In [21]:
data['溢流'].value_counts()

0    265554
1     40471
Name: 溢流, dtype: int64

## 划分X和y

## onehot

In [5]:
data_label = ['kick_0', 'kick_1']

In [6]:
data = encoded

In [7]:
X = data.drop(['时间'], axis=1)
X = X.drop(data_label, axis=1)
y = data[data_label]

### labelencoder下

In [22]:
X = data.drop(['时间'], axis=1)
y = data[['溢流']]

## 加载模型

In [23]:
from joblib import load
# Load the saved model from disk
clf = load('random_forest.joblib')

In [24]:
# Use the model for prediction
y_pred = clf.predict(X)

In [26]:
test_y = pd.DataFrame(y_pred)

In [27]:
test_y.value_counts()

0    265554
1     40471
dtype: int64

## 准确率，召回率、f1分数，看模型效果

In [25]:
from sklearn.metrics import classification_report
print(classification_report(y, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    265554
           1       1.00      1.00      1.00     40471

    accuracy                           1.00    306025
   macro avg       1.00      1.00      1.00    306025
weighted avg       1.00      1.00      1.00    306025

<font color='red'> 此处遇到问题，现有的这个井8中只有0,1两类，编码也为10，01,而不是0001,0010,0100,1000的四位编码，无法进行评估比较，故使用多分类器，one-vs-rest or one-vs-one <font>