## 使用其他井数据进行测试

In [6]:
import numpy as np
import pandas as pd
readpath = r'井8井3合并.csv'
data = pd.read_csv(readpath,encoding='GBK')
data.head()

,井深(8004) m,迟到井深(8006) m,大钩高度(8008) m,全烃(8219) %,入口温度(8106) DEG.C,泵冲次1(8059) spm,出口密度(8105) g/cm3,套管压力(8019) MPa,钻时(8020) min/m,立管压力(8018) MPa,钻压(8011) kN,入口流量(8110) L/s,出口温度(8107) DEG.C,钻头位置(8005) m,入口密度(8104) g/cm3,扭矩(8013) kN.m,大钩负荷(8010) kN,总池体积(8112) m3,溢流,转盘转速(8012) RPM
0,2962.02999,2958.93999,21.57461,1.11658,39.3488,0,1.60680,0.0,9.28820,17.82822,75.77991,1678.3872,48.8375,2962.02699,1.67270,5.11508,1154.32399,80.65078,0,54.20431
1,2962.02999,2958.93999,21.56942,1.11697,39.3488,0,1.60899,0.0,9.28820,17.97551,75.95031,1678.0662,48.8375,2962.03199,1.67509,5.07789,1154.15399,80.65187,0,54.28840
2,2962.02999,2958.93999,21.56942,1.11726,39.3488,0,1.61079,0.0,9.30390,17.84862,76.02891,1678.0662,48.8375,2962.03199,1.67938,4.95509,1154.07500,80.64898,0,54.36190
3,2962.02999,2958.93999,21.56942,1.11766,39.3488,0,1.61050,0.0,9.32050,17.64002,75.67501,1678.0662,48.8375,2962.03199,1.67548,4.96339,1154.42900,80.64329,0,54.30380
4,2962.03998,2958.93999,21.56412,1.11795,39.3488,0,1.60700,0.0,9.32149,17.65231,75.80601,1678.7082,48.8375,2962.03798,1.67389,5.11559,1154.29800,80.64139,0,54.19361

In [7]:
print("井3和8溢流标签\n",data['溢流'].value_counts())

井3和8溢流标签
 0    13296
1     4698
2     1880
Name: 溢流, dtype: int64

## 使用onehotencoder

In [8]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
encoded_kick= encoder.fit_transform(data[['溢流']])
# Create a DataFrame from the encoded data 
encoded_df = pd.DataFrame(encoded_kick.toarray(), columns=encoder.get_feature_names_out(['溢流']))
encoded_df = encoded_df.rename(columns={'溢流_0': 'kick_0', '溢流_1': 'kick_1', '溢流_2': 'kick_2'})

# Concatenate the original DataFrame and the encoded DataFrame
data = pd.concat([data, encoded_df], axis=1)
data.head()

,井深(8004) m,迟到井深(8006) m,大钩高度(8008) m,全烃(8219) %,入口温度(8106) DEG.C,泵冲次1(8059) spm,出口密度(8105) g/cm3,套管压力(8019) MPa,钻时(8020) min/m,立管压力(8018) MPa,...,钻头位置(8005) m,入口密度(8104) g/cm3,扭矩(8013) kN.m,大钩负荷(8010) kN,总池体积(8112) m3,溢流,转盘转速(8012) RPM,kick_0,kick_1,kick_2
0,2962.02999,2958.93999,21.57461,1.11658,39.3488,0,1.60680,0.0,9.28820,17.82822,...,2962.02699,1.67270,5.11508,1154.32399,80.65078,0,54.20431,1.0,0.0,0.0
1,2962.02999,2958.93999,21.56942,1.11697,39.3488,0,1.60899,0.0,9.28820,17.97551,...,2962.03199,1.67509,5.07789,1154.15399,80.65187,0,54.28840,1.0,0.0,0.0
2,2962.02999,2958.93999,21.56942,1.11726,39.3488,0,1.61079,0.0,9.30390,17.84862,...,2962.03199,1.67938,4.95509,1154.07500,80.64898,0,54.36190,1.0,0.0,0.0
3,2962.02999,2958.93999,21.56942,1.11766,39.3488,0,1.61050,0.0,9.32050,17.64002,...,2962.03199,1.67548,4.96339,1154.42900,80.64329,0,54.30380,1.0,0.0,0.0
4,2962.03998,2958.93999,21.56412,1.11795,39.3488,0,1.60700,0.0,9.32149,17.65231,...,2962.03798,1.67389,5.11559,1154.29800,80.64139,0,54.19361,1.0,0.0,0.0

In [13]:
data.drop(columns=['溢流'], inplace=True)

### onehotencoder下划分X和y

In [14]:
data_label=['kick_0','kick_1','kick_2']

In [15]:
X = data.drop(data_label, axis=1)
y = data[data_label]

In [16]:
X.head()

,井深(8004) m,迟到井深(8006) m,大钩高度(8008) m,全烃(8219) %,入口温度(8106) DEG.C,泵冲次1(8059) spm,出口密度(8105) g/cm3,套管压力(8019) MPa,钻时(8020) min/m,立管压力(8018) MPa,钻压(8011) kN,入口流量(8110) L/s,出口温度(8107) DEG.C,钻头位置(8005) m,入口密度(8104) g/cm3,扭矩(8013) kN.m,大钩负荷(8010) kN,总池体积(8112) m3,转盘转速(8012) RPM
0,2962.02999,2958.93999,21.57461,1.11658,39.3488,0,1.60680,0.0,9.28820,17.82822,75.77991,1678.3872,48.8375,2962.02699,1.67270,5.11508,1154.32399,80.65078,54.20431
1,2962.02999,2958.93999,21.56942,1.11697,39.3488,0,1.60899,0.0,9.28820,17.97551,75.95031,1678.0662,48.8375,2962.03199,1.67509,5.07789,1154.15399,80.65187,54.28840
2,2962.02999,2958.93999,21.56942,1.11726,39.3488,0,1.61079,0.0,9.30390,17.84862,76.02891,1678.0662,48.8375,2962.03199,1.67938,4.95509,1154.07500,80.64898,54.36190
3,2962.02999,2958.93999,21.56942,1.11766,39.3488,0,1.61050,0.0,9.32050,17.64002,75.67501,1678.0662,48.8375,2962.03199,1.67548,4.96339,1154.42900,80.64329,54.30380
4,2962.03998,2958.93999,21.56412,1.11795,39.3488,0,1.60700,0.0,9.32149,17.65231,75.80601,1678.7082,48.8375,2962.03798,1.67389,5.11559,1154.29800,80.64139,54.19361

## 加载模型

In [22]:
from joblib import load
# Load the saved model from disk
clf = load('random_forest_onehot.joblib')

In [23]:
# Use the model for prediction
y_pred = clf.predict(X)

In [24]:
test_y = pd.DataFrame(y_pred)

In [25]:
test_y.value_counts()

0    1    2
1.0  0.0  0.0    19874
dtype: int64

## 准确率，召回率、f1分数，看模型效果

In [26]:
from sklearn.metrics import classification_report
print(classification_report(y, y_pred))

              precision    recall  f1-score   support

           0       0.67      1.00      0.80     13296
           1       0.00      0.00      0.00      4698
           2       0.00      0.00      0.00      1880

   micro avg       0.67      0.67      0.67     19874
   macro avg       0.22      0.33      0.27     19874
weighted avg       0.45      0.67      0.54     19874
 samples avg       0.67      0.67      0.67     19874

/home/klmyty/code/ML/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))